TYPE=VIEW
query=select `tienda_de_ropa`.`aperturas_de_caja`.`FECHA` AS `FECHA`,`tienda_de_ropa`.`aperturas_de_caja`.`MONTO` AS `APERTURA`,if(isnull(`ingresos`.`MONTO`),0,`ingresos`.`MONTO`) AS `INGRESOS`,if(isnull(`egresos`.`MONTO`),0,`egresos`.`MONTO`) AS `EGRESOS`,((`tienda_de_ropa`.`aperturas_de_caja`.`MONTO` + if(isnull(`ingresos`.`MONTO`),0,`ingresos`.`MONTO`)) - if(isnull(`egresos`.`MONTO`),0,`egresos`.`MONTO`)) AS `CIERRE` from ((`tienda_de_ropa`.`aperturas_de_caja` left join (select `tienda_de_ropa`.`ingresos`.`FECHA` AS `FECHA`,sum(`tienda_de_ropa`.`ingresos`.`MONTO`) AS `MONTO` from `tienda_de_ropa`.`ingresos` where (`tienda_de_ropa`.`ingresos`.`CANCELADO` = FALSE) group by cast(`tienda_de_ropa`.`ingresos`.`FECHA` as date)) `ingresos` on((`tienda_de_ropa`.`aperturas_de_caja`.`FECHA` = cast(`ingresos`.`FECHA` as date)))) left join (select `tienda_de_ropa`.`egresos`.`FECHA` AS `FECHA`,sum(`tienda_de_ropa`.`egresos`.`MONTO`) AS `MONTO` from `tienda_de_ropa`.`egresos` where (`tienda_de_ropa`.`egresos`.`CANCELADO` = FALSE) group by cast(`tienda_de_ropa`.`egresos`.`FECHA` as date)) `egresos` on((cast(`ingresos`.`FECHA` as date) = cast(`egresos`.`FECHA` as date))))
md5=7f4c31956275afde58f17f61b15ef1d9
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2018-05-08 14:52:54
create-version=1
source=select `tienda_de_ropa`.`aperturas_de_caja`.`FECHA` AS `FECHA`,`tienda_de_ropa`.`aperturas_de_caja`.`MONTO` AS `APERTURA`,if(isnull(`ingresos`.`MONTO`),0,`ingresos`.`MONTO`) AS `INGRESOS`,if(isnull(`egresos`.`MONTO`),0,`egresos`.`MONTO`) AS `EGRESOS`,((`tienda_de_ropa`.`aperturas_de_caja`.`MONTO` + if(isnull(`ingresos`.`MONTO`),0,`ingresos`.`MONTO`)) - if(isnull(`egresos`.`MONTO`),0,`egresos`.`MONTO`)) AS `CIERRE` from ((`tienda_de_ropa`.`aperturas_de_caja` left join (select `tienda_de_ropa`.`ingresos`.`FECHA` AS `FECHA`,sum(`tienda_de_ropa`.`ingresos`.`MONTO`) AS `MONTO` from `tienda_de_ropa`.`ingresos` where (`tienda_de_ropa`.`ingresos`.`CANCELADO` = FALSE) group by cast(`tienda_de_ropa`.`ingresos`.`FECHA` as date)) `ingresos` on((`tienda_de_ropa`.`aperturas_de_caja`.`FECHA` = cast(`ingresos`.`FECHA` as date)))) left join (select `tienda_de_ropa`.`egresos`.`FECHA` AS `FECHA`,sum(`tienda_de_ropa`.`egresos`.`MONTO`) AS `MONTO` from `tienda_de_ropa`.`egresos` where (`tienda_de_ropa`.`egresos`.`CANCELADO` = FALSE) group by cast(`tienda_de_ropa`.`egresos`.`FECHA` as date)) `egresos` on((cast(`ingresos`.`FECHA` as date) = cast(`egresos`.`FECHA` as date))))
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `tienda_de_ropa`.`aperturas_de_caja`.`FECHA` AS `FECHA`,`tienda_de_ropa`.`aperturas_de_caja`.`MONTO` AS `APERTURA`,if(isnull(`ingresos`.`MONTO`),0,`ingresos`.`MONTO`) AS `INGRESOS`,if(isnull(`egresos`.`MONTO`),0,`egresos`.`MONTO`) AS `EGRESOS`,((`tienda_de_ropa`.`aperturas_de_caja`.`MONTO` + if(isnull(`ingresos`.`MONTO`),0,`ingresos`.`MONTO`)) - if(isnull(`egresos`.`MONTO`),0,`egresos`.`MONTO`)) AS `CIERRE` from ((`tienda_de_ropa`.`aperturas_de_caja` left join (select `tienda_de_ropa`.`ingresos`.`FECHA` AS `FECHA`,sum(`tienda_de_ropa`.`ingresos`.`MONTO`) AS `MONTO` from `tienda_de_ropa`.`ingresos` where (`tienda_de_ropa`.`ingresos`.`CANCELADO` = FALSE) group by cast(`tienda_de_ropa`.`ingresos`.`FECHA` as date)) `ingresos` on((`tienda_de_ropa`.`aperturas_de_caja`.`FECHA` = cast(`ingresos`.`FECHA` as date)))) left join (select `tienda_de_ropa`.`egresos`.`FECHA` AS `FECHA`,sum(`tienda_de_ropa`.`egresos`.`MONTO`) AS `MONTO` from `tienda_de_ropa`.`egresos` where (`tienda_de_ropa`.`egresos`.`CANCELADO` = FALSE) group by cast(`tienda_de_ropa`.`egresos`.`FECHA` as date)) `egresos` on((cast(`ingresos`.`FECHA` as date) = cast(`egresos`.`FECHA` as date))))
