TYPE=VIEW
query=select `tienda_de_ropa`.`clientes`.`ID` AS `ID`,concat(`tienda_de_ropa`.`clientes`.`NOMBRE`,\' \',`tienda_de_ropa`.`clientes`.`APELLIDO_PATERNO`,\' \',`tienda_de_ropa`.`clientes`.`APELLIDO_MATERNO`) AS `NOMBRE` from `tienda_de_ropa`.`clientes`
md5=ea0c6f336bf4dca25cf89d2f0881e284
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2018-05-08 14:52:54
create-version=1
source=select `clientes`.`ID` AS `ID`,concat(`clientes`.`NOMBRE`,\' \',`clientes`.`APELLIDO_PATERNO`,\' \',`clientes`.`APELLIDO_MATERNO`) AS `NOMBRE` from `clientes`
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `tienda_de_ropa`.`clientes`.`ID` AS `ID`,concat(`tienda_de_ropa`.`clientes`.`NOMBRE`,\' \',`tienda_de_ropa`.`clientes`.`APELLIDO_PATERNO`,\' \',`tienda_de_ropa`.`clientes`.`APELLIDO_MATERNO`) AS `NOMBRE` from `tienda_de_ropa`.`clientes`
