ALTER TABLE ABONOS DISCARD TABLESPACE;
ALTER TABLE ABONOS IMPORT TABLESPACE;

ALTER TABLE APARTADOS DISCARD TABLESPACE;
ALTER TABLE APARTADOS IMPORT TABLESPACE;

ALTER TABLE APARTADOS_ASIGNACIONES DISCARD TABLESPACE;
ALTER TABLE APARTADOS_ASIGNACIONES IMPORT TABLESPACE;

ALTER TABLE APARTADOS_POR_CLIENTE DISCARD TABLESPACE;
ALTER TABLE APARTADOS_POR_CLIENTE IMPORT TABLESPACE;

ALTER TABLE APERTURAS_DE_CAJA DISCARD TABLESPACE;
ALTER TABLE APERTURAS_DE_CAJA IMPORT TABLESPACE;

ALTER TABLE BUSCAR_POR_SUBFOLIO DISCARD TABLESPACE;
ALTER TABLE BUSCAR_POR_SUBFOLIO IMPORT TABLESPACE;


ALTER TABLE CATEGORIAS DISCARD TABLESPACE;
ALTER TABLE CATEGORIAS IMPORT TABLESPACE;

ALTER TABLE CLIENTES DISCARD TABLESPACE;
ALTER TABLE CLIENTES IMPORT TABLESPACE;

ALTER TABLE CLIENTES_CON_FORMATO DISCARD TABLESPACE;
ALTER TABLE CLIENTES_CON_FORMATO IMPORT TABLESPACE;

ALTER TABLE COMPRA_DETALLE DISCARD TABLESPACE;
ALTER TABLE COMPRA_DETALLE IMPORT TABLESPACE;

ALTER TABLE COMPRAS DISCARD TABLESPACE;
ALTER TABLE COMPRAS IMPORT TABLESPACE;

ALTER TABLE COMPRAS_PRODUCTOS DISCARD TABLESPACE;
ALTER TABLE COMPRAS_PRODUCTOS IMPORT TABLESPACE;

ALTER TABLE CONSULTA_PRODUCTO DISCARD TABLESPACE;
ALTER TABLE CONSULTA_PRODUCTO IMPORT TABLESPACE;

ALTER TABLE CONSULTAS DISCARD TABLESPACE;
ALTER TABLE CONSULTAS IMPORT TABLESPACE;

ALTER TABLE CORTE_CAJA DISCARD TABLESPACE;
ALTER TABLE CORTE_CAJA IMPORT TABLESPACE;

ALTER TABLE DB DISCARD TABLESPACE;
ALTER TABLE DB IMPORT TABLESPACE;

ALTER TABLE DETALLE_VENTA DISCARD TABLESPACE;
ALTER TABLE DETALLE_VENTA IMPORT TABLESPACE;

ALTER TABLE DETALLES_APARTADOS DISCARD TABLESPACE;
ALTER TABLE DETALLES_APARTADOS IMPORT TABLESPACE;

ALTER TABLE DETALLES_PRODUCTOS DISCARD TABLESPACE;
ALTER TABLE DETALLES_PRODUCTOS IMPORT TABLESPACE;

ALTER TABLE DETALLES_VENTAS_PENDIENTES DISCARD TABLESPACE;
ALTER TABLE DETALLES_VENTAS_PENDIENTES IMPORT TABLESPACE;

ALTER TABLE EGRESOS DISCARD TABLESPACE;
ALTER TABLE EGRESOS IMPORT TABLESPACE;

ALTER TABLE FORMAS_DE_PAGO DISCARD TABLESPACE;
ALTER TABLE FORMAS_DE_PAGO IMPORT TABLESPACE;

ALTER TABLE INGRESOS DISCARD TABLESPACE;
ALTER TABLE INGRESOS IMPORT TABLESPACE;

ALTER TABLE INVENTARIO DISCARD TABLESPACE;
ALTER TABLE INVENTARIO IMPORT TABLESPACE;

ALTER TABLE NIVELES_USUARIO DISCARD TABLESPACE;
ALTER TABLE NIVELES_USUARIO IMPORT TABLESPACE;

ALTER TABLE NOMBRE_CLIENTE DISCARD TABLESPACE;
ALTER TABLE NOMBRE_CLIENTE IMPORT TABLESPACE;

ALTER TABLE PAGOS_DE_CONTADO DISCARD TABLESPACE;
ALTER TABLE PAGOS_DE_CONTADO IMPORT TABLESPACE;

ALTER TABLE PRODUCTOS DISCARD TABLESPACE;
ALTER TABLE PRODUCTOS IMPORT TABLESPACE;

ALTER TABLE PRODUCTOS_PARA_VENTA DISCARD TABLESPACE;
ALTER TABLE PRODUCTOS_PARA_VENTA IMPORT TABLESPACE;

ALTER TABLE PRODUCTOS_POR_APARTADOS DISCARD TABLESPACE;
ALTER TABLE PRODUCTOS_POR_APARTADOS IMPORT TABLESPACE;

ALTER TABLE REPORTE_COMPRAS DISCARD TABLESPACE;
ALTER TABLE REPORTE_COMPRAS IMPORT TABLESPACE;

ALTER TABLE REPORTE_CONSULTAS DISCARD TABLESPACE;
ALTER TABLE REPORTE_CONSULTAS IMPORT TABLESPACE;

ALTER TABLE REPORTE_EGRESOS DISCARD TABLESPACE;
ALTER TABLE REPORTE_EGRESOS IMPORT TABLESPACE;

ALTER TABLE REPORTE_INGRESOS DISCARD TABLESPACE;
ALTER TABLE REPORTE_INGRESOS IMPORT TABLESPACE;

ALTER TABLE REPORTE_VENTA DISCARD TABLESPACE;
ALTER TABLE REPORTE_VENTA IMPORT TABLESPACE;

ALTER TABLE SUMA_EGRESOS DISCARD TABLESPACE;
ALTER TABLE SUMA_EGRESOS IMPORT TABLESPACE;

ALTER TABLE SUMA_INGRESOS DISCARD TABLESPACE;
ALTER TABLE SUMA_INGRESOS IMPORT TABLESPACE;

ALTER TABLE TIPOS_EGRESOS DISCARD TABLESPACE;
ALTER TABLE TIPOS_EGRESOS IMPORT TABLESPACE;

ALTER TABLE TIPOS_INGRESOS DISCARD TABLESPACE;
ALTER TABLE TIPOS_INGRESOS IMPORT TABLESPACE;

ALTER TABLE USUARIOS DISCARD TABLESPACE;
ALTER TABLE USUARIOS IMPORT TABLESPACE;

ALTER TABLE VENTAS DISCARD TABLESPACE;
ALTER TABLE VENTAS IMPORT TABLESPACE;

ALTER TABLE VENTAS_PENDIENTES DISCARD TABLESPACE;
ALTER TABLE VENTAS_PENDIENTES IMPORT TABLESPACE;

ALTER TABLE VENTAS_PRODUCTOS DISCARD TABLESPACE;
ALTER TABLE VENTAS_PRODUCTOS IMPORT TABLESPACE;

