INSERT INTO CATEGORIAS(NOMBRE) VALUES('TENIS PARA CORRER'),('TENIS CASUALES');

INSERT INTO FORMAS_DE_PAGO(NOMBRE) VALUES
("Efectivo"), ("Apartado"), ("Tarjeta"),  ("Pendiente");

INSERT INTO TIPOS_INGRESOS(TIPO) VALUES
("Abono"), ("Recarga"), ("Pago de contado");

INSERT INTO TIPOS_EGRESOS(TIPO) VALUES
("Proveedor"), ("Servicios"), ("Compra de mercancia"); 

INSERT INTO PRODUCTOS(CLAVE,NOMBRE,NUEVO,ID_CATEGORIA,PRECIO, DETALLES, IMAGEN)
VALUES
('1234567890','Tenis Nike azules talla 6', TRUE, 1, 1200.00,'', ''),
('15410600', 'Tenis Nike verdes talla 6', TRUE, 1, 1000,'',''),
('6491139249', 'Tenis Nike rojos talla 6', FALSE, 1, 400, '', ''),
('MARCA', 'Marca Patito zapatos', TRUE, 1, 100, '', 'C:carpeta/init.sql');

INSERT INTO CLIENTES(NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, TELEFONO1, TELEFONO2)
VALUES('Raul', 'Mendez', 'Grado', '6491139249', ''),
		('Adrian', 'Fernandez', 'Navarro', '6271338095',''),
		('Publico', 'General', '', '0000000000','');

INSERT INTO NIVELES_USUARIO(ID, NOMBRE) VALUES
	(0, "Superusuario");		
		
INSERT INTO USUARIOS(NOMBRE, CONTRASENIA, ID_NIVEL, ACTIVO)
VALUES('RaulMendezGrado','RaulMendez','0',true);

INSERT INTO VENTAS(ID_USUARIO, FORMA_PAGO, ID_CLIENTE, TOTAL)VALUES
	(1, "Efectivo", 1, 2200.00);
INSERT INTO VENTAS_PRODUCTOS(FOLIO_VENTA, CLAVE_PRODUCTO, PRECIO) VALUES
	(1,'1234567890', 1200.00), (1, '15410600', 1000);
INSERT INTO INGRESOS(ID_USUARIO,TIPO,MONTO,DETALLES) VALUES
	(1, "Pago de contado", 2200.00, "Pago de venta");
INSERT INTO PAGOS_DE_CONTADO(FOLIO_VENTA, FOLIO_INGRESO)VALUES
	(1,1);

	
	
INSERT INTO VENTAS(ID_USUARIO, FORMA_PAGO, ID_CLIENTE, TOTAL)VALUES
	(1, "Apartado", 1, 1000);
INSERT INTO VENTAS_PRODUCTOS(FOLIO_VENTA, CLAVE_PRODUCTO, PRECIO) VALUES
	(2, '15410600', 1000);
INSERT INTO APARTADOS(ID_ASIGNACION, ID_CLIENTE, COSTO, SALDO_PENDIENTE)
	VALUES(3, 1, 1000.00, 800.00);
INSERT INTO INGRESOS(ID_USUARIO,TIPO,MONTO,DETALLES)
	VALUES(1,"Abono",200.00,'');
INSERT INTO ABONOS(FOLIO_TICKET, FOLIO_APARTADO)
VALUES(1,1);

/*UPDATE PRODUCTOS SET EXISTENCIA=EXISTENCIA+1 WHERE CLAVE='1234567890';*/