/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import BaseDeDatos.SQLConnection;
import java.awt.Component;
import java.awt.Frame;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Raul
 */
public class ConsultarProducto extends javax.swing.JDialog {

    private int idUsuario = 0;
    
    /**
     * Creates new form ConsultarProducto
     */
    private ConsultarProducto(Frame parent, boolean modal, int idUsuario) {
        super(parent, modal);
        initComponents();
        
        this.idUsuario = idUsuario;                 
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtBuscarClave = new Utilidades.JTextfieldPlaceHolder();
        jSeparator1 = new javax.swing.JSeparator();
        txtClave = new Utilidades.JTextfieldPlaceHolder();
        txtNombre = new Utilidades.JTextfieldPlaceHolder();
        txtPrecio = new Utilidades.JTextfieldPlaceHolder();
        txtExistencia = new Utilidades.JTextfieldPlaceHolder();
        lblImagen = new javax.swing.JLabel();
        txtCategoria = new Utilidades.JTextfieldPlaceHolder();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Consultar Producto");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtBuscarClave.setPlaceholder("Clave");
        txtBuscarClave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscarClaveMouseClicked(evt);
            }
        });
        txtBuscarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarClaveActionPerformed(evt);
            }
        });

        txtClave.setPlaceholder("Clave");

        txtNombre.setPlaceholder("Nombre");

        txtPrecio.setPlaceholder("Precio");

        txtExistencia.setPlaceholder("Existencia");

        lblImagen.setBackground(new java.awt.Color(255, 255, 255));
        lblImagen.setOpaque(true);
        lblImagen.setPreferredSize(new java.awt.Dimension(150, 150));

        txtCategoria.setPlaceholder("Categoria");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscarClave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBuscar))
                    .addComponent(jSeparator1)
                    .addComponent(txtClave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtBuscarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarClaveActionPerformed
        buscar();
    }//GEN-LAST:event_txtBuscarClaveActionPerformed

    private void txtBuscarClaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarClaveMouseClicked
        txtBuscarClave.setText(BuscarProducto.mostrar(null));
    }//GEN-LAST:event_txtBuscarClaveMouseClicked

    public static void mostrar(Frame parent, int idUsuario){
        ConsultarProducto dialogo = new ConsultarProducto(parent, true, idUsuario);
        
        dialogo.setVisible(true);
        dialogo.dispose();
    }    

    private void buscar(){
        try {
            String sql = "SELECT * FROM CONSULTA_PRODUCTO WHERE CLAVE='" + txtBuscarClave.getText() + "'";
            String registrarConsulta = "INSERT INTO CONSULTAS(CLAVE_PRODUCTO, ID_USUARIO) "
                    + "VALUES("
                    + "'" + txtBuscarClave.getText() + "',"
                    + idUsuario + ")";
                        
            ResultSet consulta = SQLConnection.select(sql);            
            if(consulta.next()){
                if(SQLConnection.update(registrarConsulta)){
                    txtClave.setText(consulta.getString("CLAVE"));
                    txtNombre.setText(consulta.getString("NOMBRE"));
                    txtCategoria.setText(consulta.getString("CATEGORIA"));
                    txtPrecio.setText("$"+consulta.getString("PRECIO"));
                    txtExistencia.setText(consulta.getString("EXISTENCIA") + " piezas");
                    lblImagen.setIcon(new ImageIcon(new ImageIcon(consulta.getString("IMAGEN"))
                            .getImage().getScaledInstance(150, 150, Image.SCALE_DEFAULT)));
                }else{
                    JOptionPane.showMessageDialog(
                        this, 
                        "No se puede mostrar el artículo",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(
                        this, 
                        "No se pudo encontrar el artículo",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ConsultarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblImagen;
    private Utilidades.JTextfieldPlaceHolder txtBuscarClave;
    private Utilidades.JTextfieldPlaceHolder txtCategoria;
    private Utilidades.JTextfieldPlaceHolder txtClave;
    private Utilidades.JTextfieldPlaceHolder txtExistencia;
    private Utilidades.JTextfieldPlaceHolder txtNombre;
    private Utilidades.JTextfieldPlaceHolder txtPrecio;
    // End of variables declaration//GEN-END:variables
}
