/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import BaseDeDatos.SQLConnection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Raul
 */
public class ConsultarTransaccion extends javax.swing.JDialog {

    int idUsuario = 0;
    
    /**
     * Creates new form ConsultarTransaccion
     */
    private ConsultarTransaccion(java.awt.Frame parent, boolean modal, int idUsuario) {
        super(parent, modal);
        
        initComponents();
        
        setLocationRelativeTo(null);
        this.idUsuario = idUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboTipo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtFolio = new javax.swing.JFormattedTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Consultar Transacción");

        jLabel2.setText("Tipo");

        cboTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ingreso", "Egreso", "Venta", "Compra" }));

        jLabel3.setText("Folio");

        txtFolio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFolioActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFolio, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cboTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        consultar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFolioActionPerformed
        consultar();
    }//GEN-LAST:event_txtFolioActionPerformed

    public static void mostrar(JFrame parent, int idUsuario){
        ConsultarTransaccion dialogo = new ConsultarTransaccion(parent, true, idUsuario);
        
        dialogo.setVisible(true);
        dialogo.dispose();
    }
     
    private void consultar(){
        String tipo = cboTipo.getSelectedItem().toString();        
        int folio = Integer.parseInt(txtFolio.getText());
        try {
            if (tipo.equalsIgnoreCase("INGRESO")) {

                String sql = "SELECT FOLIO FROM INGRESOS WHERE FOLIO=" + folio;

                ResultSet consulta = SQLConnection.select(sql);

                if (consulta.next()){
                    setVisible(false);
                    dispose();
                    Ingreso.mostrar(null, idUsuario, folio);
                }else 
                    JOptionPane.showMessageDialog(this, "Folio no encontrado");                
            } else if (tipo.equalsIgnoreCase("EGRESO")) {

                String sql = "SELECT FOLIO FROM EGRESOS WHERE FOLIO=" + folio;

                ResultSet consulta = SQLConnection.select(sql);

                if (consulta.next()){
                    setVisible(false);
                    dispose();
                    Egreso.mostrar(null, idUsuario, folio);
                }else 
                    JOptionPane.showMessageDialog(this, "Folio no encontrado");                
            } else if (tipo.equalsIgnoreCase("COMPRA")) {

                String sql = "SELECT FOLIO FROM COMPRAS WHERE FOLIO=" + folio;               
                
                ResultSet consulta = SQLConnection.select(sql);

                if (consulta.next()){
                    setVisible(false);
                    dispose();
                    EntradaMercancia.mostrar(null, idUsuario, folio);
                }else 
                    JOptionPane.showMessageDialog(this, "Folio no encontrado");                
            }else if (tipo.equalsIgnoreCase("VENTA")) {

                String sql = "SELECT FOLIO FROM REPORTE_VENTA WHERE FOLIO=" + folio;               
                
                ResultSet consulta = SQLConnection.select(sql);

                if (consulta.next()){
                    setVisible(false);
                    dispose();
                    Venta.mostrar(null, idUsuario, folio);
                }else 
                    JOptionPane.showMessageDialog(this, "Folio no encontrado");                
            }
        } catch (SQLException ex) {
            Logger.getLogger(ConsultarTransaccion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox cboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JFormattedTextField txtFolio;
    // End of variables declaration//GEN-END:variables
}
