/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import BaseDeDatos.SQLConnection;
import Utilidades.Fecha;
import Utilidades.Seguridad;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Raul
 */
public class Egreso extends javax.swing.JDialog {

    private static final int NUEVO = 1;
    private static final int VER = 2;
    private static final int NUEVO_PARA_PAGO = 3;
    
    private int idUsuarioActual;
    private int folioActual = 0;    
    
    private int uso;
    
    /**
     * Creates new form Egreso
     */
    private Egreso(java.awt.Frame parent, boolean modal, int idUsuarioActual, int uso) {
        super(parent, modal);
        initComponents();
        
        this.idUsuarioActual = idUsuarioActual;
        this.uso = uso;
        
        btnEliminar.setEnabled(false);
        btnAceptar.setEnabled(false);
        
        txtFecha.setText(Fecha.hoy());
        
        cargarParaNuevo();                
    }

    private Egreso(java.awt.Frame parent, boolean modal, int idUsuarioActual, int uso, int folio) {
        super(parent, modal);
        initComponents();
        
        this.idUsuarioActual = idUsuarioActual;
        this.folioActual = folio;
        this.uso = uso;
        
        btnEliminar.setEnabled(false);
        btnAceptar.setEnabled(false);
        
        txtFecha.setText(Fecha.hoy());
        
        cargarEgreso();                
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMonto = new javax.swing.JFormattedTextField();
        btnEliminar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cboTipo = new javax.swing.JComboBox();
        txtUsuario = new javax.swing.JTextField();
        txtFolio = new javax.swing.JTextField();
        txtFecha = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        chkCancelado = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetalles = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtMonto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("$#,##0.00"))));
        txtMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel6.setText("Tipo");

        jLabel8.setText("Usuario");

        cboTipo.setEditable(true);
        cboTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTipoItemStateChanged(evt);
            }
        });

        txtUsuario.setEditable(false);

        txtFolio.setEditable(false);

        txtFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy/MM/dd"))));

        jLabel7.setText("Detalles");

        chkCancelado.setText("Cancelado");
        chkCancelado.setEnabled(false);

        jLabel2.setText("Folio");

        jLabel3.setText("Fecha");

        btnCancelar.setText("Cerrar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtDetalles.setColumns(20);
        txtDetalles.setRows(5);
        jScrollPane1.setViewportView(txtDetalles);

        jLabel5.setText("Monto");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Egreso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtUsuario))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFecha)
                            .addComponent(txtFolio)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkCancelado)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                                .addComponent(btnCancelar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAceptar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkCancelado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAceptar)
                        .addComponent(btnCancelar))
                    .addComponent(btnEliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Random r = new Random(System.nanoTime());

        int folio = Integer.parseInt(txtFolio.getText());
        String fecha = txtFecha.getText();
        int digitoValidador = Math.abs(r.nextInt())%1000000000;        

        String ing = JOptionPane.showInputDialog(
            "Se requiere autorización para realizar esta acción\n"
            + "Proporcione los siguientes datos:\n"
            + "Folio:" + txtFolio.getText() + "\n"
            + "Fecha:" + txtFecha.getText() + "\n"
            + "Usuario:" + idUsuarioActual + "\n"
            + "Número de validación:" + digitoValidador + "\n\n"
            + "Ingrese el código de autorización:");
        if(Seguridad.checkEliminarEgreso(
            folio,
            fecha,
            idUsuarioActual,
            digitoValidador,
            ing)){        
        String sqlCancelar = "UPDATE EGRESOS SET CANCELADO=TRUE WHERE FOLIO=" + folio;        

        if(!SQLConnection.update(sqlCancelar)){
            JOptionPane.showMessageDialog(
                this,
                "No fue posible cancelar el ingreso",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            SQLConnection.rollback();
            return;
        }
        
        JOptionPane.showMessageDialog(
            this,
            "¡Egreso cancelado!");
        setVisible(false);
        dispose();
        }else{
            JOptionPane.showMessageDialog(
                this,
                "Código incorrecto",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void cboTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTipoItemStateChanged
        
    }//GEN-LAST:event_cboTipoItemStateChanged

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if(JOptionPane.showConfirmDialog(
            this,
            "¿Seguro que desea cancelar?",
            "Confirmación",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
        setVisible(false);
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String insertIngreso = "INSERT INTO EGRESOS("
        + "FECHA,"
        + "ID_USUARIO,"
        + "TIPO,"
        + "MONTO,"
        + "DETALLES)"
        + "VALUES("
        + "NOW(),"
        + idUsuarioActual + ","
        + "'" + cboTipo.getSelectedItem() + "',"
        + txtMonto.getText() + ","
        + "'" + txtDetalles.getText() + "');";                  
        
        if(SQLConnection.update(insertIngreso)){                          
            if(uso == NUEVO_PARA_PAGO){
                try {
                    String sql = "SELECT MAX(FOLIO) AS FOLIO FROM EGRESOS";
                    
                    ResultSet consulta = SQLConnection.select(sql);                    
                    
                    if(consulta.next())
                        folioActual = consulta.getInt("FOLIO");
                } catch (SQLException ex) {
                    Logger.getLogger(Egreso.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            JOptionPane.showMessageDialog(this, "Ingreso guardado correctamente");
            setVisible(false);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    public static void nuevo(JFrame parent, int idUsuarioActual){
        Egreso egreso = new Egreso(parent, true, idUsuarioActual, NUEVO);
        
        egreso.setVisible(true);
        egreso.dispose();        
    }
    
    public static int nuevoCompra(JFrame parent, int idUsusarioActual, float monto){
        Egreso egreso = new Egreso(parent, true, idUsusarioActual, NUEVO_PARA_PAGO);
        
        egreso.cboTipo.setSelectedItem("Compra de mercancia");        
        egreso.txtMonto.setText(monto + "");
        
        egreso.cboTipo.setEnabled(false);
        egreso.txtMonto.setEnabled(false);
        
        egreso.setVisible(true);
        egreso.dispose();
        
        System.out.println(egreso.folioActual);
        
        return egreso.folioActual;
    }
    
    public static void mostrar(JFrame parent, int idUsuarioActual, int folio){
        Egreso egreso = new Egreso(parent, true, idUsuarioActual, VER, folio);
        
        egreso.btnEliminar.setEnabled(egreso.chkCancelado.isSelected());
        
        egreso.setVisible(true);
        egreso.dispose();
    }
    
    private void cargarParaNuevo(){
        
        try {
            String sqlIngreso = "SELECT * FROM TIPOS_EGRESOS";
            String sqlUsuario = "SELECT NOMBRE FROM USUARIOS WHERE ID=" + idUsuarioActual;
            
            ResultSet consulta = SQLConnection.select(sqlIngreso);
            
            while(consulta.next()){
                String tipo = consulta.getString("TIPO");
                
                ((DefaultComboBoxModel)cboTipo.getModel()).
                        addElement(tipo);                
            }
            
            consulta = SQLConnection.select(sqlUsuario);
                        
            if(consulta.next()){
                txtUsuario.setText(consulta.getString("NOMBRE"));                
            }
            
            btnAceptar.setEnabled(true);
        } catch (SQLException ex) {
            Logger.getLogger(Egreso.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        
    
    private void cargarEgreso(){
        String sql = "";
        
        try {                        
            sql = "SELECT * FROM REPORTE_EGRESOS WHERE FOLIO=" + folioActual;                        
            
            ResultSet consulta = SQLConnection.select(sql);
            if(consulta.next()){
                txtFolio.setText(consulta.getString("FOLIO"));
                txtFecha.setText(consulta.getString("FECHA"));
                txtMonto.setText(consulta.getString("MONTO"));
                txtDetalles.setText(consulta.getString("DETALLES"));
                txtUsuario.setText(consulta.getString("USUARIO"));
                chkCancelado.setSelected(consulta.getBoolean("CANCELADO"));
                ((DefaultComboBoxModel<String>)cboTipo.getModel()).addElement(
                        consulta.getString("TIPO")
                );                                
                
                cboTipo.setEnabled(false);
                btnEliminar.setEnabled(!consulta.getBoolean("CANCELADO"));                        
            }
        } catch (SQLException ex) {
            Logger.getLogger(Egreso.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Egreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Egreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Egreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Egreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Egreso.nuevo(null, 1);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox cboTipo;
    private javax.swing.JCheckBox chkCancelado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDetalles;
    private javax.swing.JFormattedTextField txtFecha;
    private javax.swing.JTextField txtFolio;
    private javax.swing.JFormattedTextField txtMonto;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
