TYPE=VIEW
query=select `tienda_de_ropa`.`productos`.`CLAVE` AS `CLAVE`,`tienda_de_ropa`.`productos`.`NOMBRE` AS `NOMBRE`,`tienda_de_ropa`.`productos`.`PRECIO` AS `PRECIO` from `tienda_de_ropa`.`productos`
md5=c27f418bba42c048d37d75b53a692d74
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2018-03-09 22:08:33
create-version=1
source=select `productos`.`CLAVE` AS `CLAVE`,`productos`.`NOMBRE` AS `NOMBRE`,`productos`.`PRECIO` AS `PRECIO` from `productos`
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `tienda_de_ropa`.`productos`.`CLAVE` AS `CLAVE`,`tienda_de_ropa`.`productos`.`NOMBRE` AS `NOMBRE`,`tienda_de_ropa`.`productos`.`PRECIO` AS `PRECIO` from `tienda_de_ropa`.`productos`
